### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by JasonBarnabe** [patricklindsay/wice_grid#70]
I got myself added as a maintainer to this project as it was used by employer. I am no longer with that employer and have no projects that use this gem. I will not be making changes or reviewing pull requests going forward.

If you'd like to take on a maintenance role with this project, please ping me.

**Comment by kreintjes** [comment]
@JasonBarnabe I might be interested in taking on a maintainer role since my company is still using WiceGrid for an older application (currently Rails 5.1 but in the process of being upgraded tot 6.0) and we are considering to use it for a new project as well.

We will first upgrade the older application to Rails 6 and see how well WiceGrid works with it or if it can be easily fixed to support Rails 6. Based on that we will decide if we continue using WiceGrid. Will keep you posted.

To make this process go faster it would be helpful if you could answer my question regarding the Rails 5.2 deprecations: https://github.com/patricklindsay/wice_grid/pull/41#issuecomment-574685642

Thanks to you and @patricklindsay for maintaining the gem these past years!

**Comment by JasonBarnabe** [comment]
@patricklindsay Can you add kreintjes as a maintainer or give me permission to do it myself?

**Comment by kreintjes** [comment]
@patricklindsay @leikind I would like to become a maintainer and get WiceGrid up to date for Rails 6. Could you add me as a maintainer to either this fork or the original (leikind's) and give me access to RubyGems (or reserve some time to do a release a few times a year yourselves).

Btw, I'm already running [my fork](https://github.com/kreintjes/wice_grid/tree/fix/all) with some small changes on a Rails 6 project without any problems, but need to get the test suite working again and running against Rails 6 as well.

Thanks for the great gem!

**Comment by patricklindsay** [comment]
Sounds great. Thanks for helping out @kreintjes !

I've added you as a collaborator on this repo 🎉

**Comment by kreintjes** [comment]
@patricklindsay @JasonBarnabe @leikind To be honest I'm having difficulties to find the time to give this gem/repo the maintenance it needs. I have done some work in my own fork to get it up to running with Rails 6.0 and 6.1, but I'm reluctant to merge or fix stuff in this repo because of the broken CI. I'm also unsure how much longer I will be using wice_grid myself (I'm only using it for one app, whose future is currently uncertain).

Is there any chance one of you wants to takeover the maintenance again? Otherwise I will put up signs in the readme/issues that this project is no longer actively maintained and looking for new maintainers.
